/**
 * Layer 4: Full AI Summarization
 *
 * The heaviest compression layer - uses an AI model to generate
 * a natural language summary of the conversation history.
 */

import { type Message, estimateMessageTokens } from './tokenEstimation.js';

export interface FullCompactConfig {
  // Number of recent messages to keep intact
  windowMessages: number;
  // Model to use for summarization
  model?: string;
  // Max tokens for the summary
  summaryMaxTokens: number;
}

export const DEFAULT_FULL_COMPACT_CONFIG: FullCompactConfig = {
  windowMessages: 50,
  summaryMaxTokens: 10_000,
};

export interface FullCompactResult {
  messages: Message[];
  summary: string;
  triggered: boolean;
  compactedCount: number;
}

/**
 * Strip heavy content from messages (images -> markers).
 */
function stripHeavyContent(messages: Message[]): Message[] {
  return messages.map((msg) => {
    const content = msg.message?.content || msg.content;

    if (!Array.isArray(content)) {
      return msg;
    }

    const strippedContent = content.map((block) => {
      if (block.type === 'image') {
        return { ...block, text: '[image]', content: '[image]' };
      }
      if (block.type === 'document') {
        return { ...block, text: '[document]', content: '[document]' };
      }
      return block;
    });

    if (strippedContent === content) {
      return msg;
    }

    return {
      ...msg,
      message: { ...msg.message, content: strippedContent },
    };
  });
}

/**
 * Extract text content from messages for summarization.
 */
function extractTextForSummary(messages: Message[]): string {
  const lines: string[] = [];

  for (const msg of messages) {
    const content = msg.message?.content || msg.content;
    const role = msg.role || msg.type;
    const time = msg.timestamp || '';

    if (!Array.isArray(content)) {
      continue;
    }

    for (const block of content) {
      if (block.type === 'text' && block.text) {
        lines.push(`[${role} ${time}]: ${block.text}`);
      }
    }
  }

  return lines.join('\n');
}

/**
 * Build the summary prompt.
 */
function buildSummaryPrompt(conversationText: string, context: string): string {
  return `You are a conversation summarizer. Your task is to create a concise summary of the following conversation that preserves all important information, decisions, and context.

## Requirements:
- Preserve specific facts, names, dates, and technical details
- Keep the overall narrative and reasoning flow
- Note any important unresolved questions or follow-up items
- Summarize in the same language as the conversation

## Conversation to Summarize:

${conversationText}

## Summary:`;
}

/**
 * Generate a summary using an AI model.
 *
 * In a real implementation, this would call the configured AI API.
 * For now, this is a placeholder that simulates the behavior.
 */
async function generateSummary(
  conversationText: string,
  config: FullCompactConfig,
  modelClient?: {
    summarize: (prompt: string, maxTokens: number) => Promise<string>;
  }
): Promise<string> {
  if (modelClient) {
    const prompt = buildSummaryPrompt(conversationText, '');
    return modelClient.summarize(prompt, config.summaryMaxTokens);
  }

  // Placeholder: In real implementation, this would call MiniMax/Claude API
  // For now, return a mock summary indicating how many messages were summarized
  const msgCount = conversationText.split('\n').length;
  return `[Summary of ${msgCount} conversation messages - In production, this would be generated by AI]`;
}

/**
 * Create a boundary message marking the compaction.
 */
function createBoundaryMessage(
  summary: string,
  originalMessageCount: number,
  recentMessageCount: number
): Message {
  return {
    id: `compact-boundary-${Date.now()}`,
    type: 'system',
    timestamp: new Date().toISOString(),
    message: {
      content: [
        {
          type: 'text',
          text: `[Context Compaction] Earlier conversation summarized. Original: ${originalMessageCount} messages → ${recentMessageCount} recent messages kept.\n\nSummary:\n${summary}`,
        },
      ],
    },
  };
}

/**
 * Perform full AI summarization compaction.
 */
export async function fullCompact(
  messages: Message[],
  config: FullCompactConfig = DEFAULT_FULL_COMPACT_CONFIG,
  modelClient?: {
    summarize: (prompt: string, maxTokens: number) => Promise<string>;
  }
): Promise<FullCompactResult> {
  if (messages.length <= config.windowMessages) {
    return {
      messages,
      summary: '',
      triggered: false,
      compactedCount: 0,
    };
  }

  // Strip heavy content first
  const stripped = stripHeavyContent(messages);

  // Split into messages to keep and messages to summarize
  const recentMessages = stripped.slice(-config.windowMessages);
  const olderMessages = stripped.slice(0, -config.windowMessages);

  // Extract text from older messages for summarization
  const textForSummary = extractTextForSummary(olderMessages);

  // Generate summary using AI
  const summary = await generateSummary(textForSummary, config, modelClient);

  // Create boundary message with summary
  const boundary = createBoundaryMessage(
    summary,
    olderMessages.length,
    recentMessages.length
  );

  // Return boundary + recent messages
  return {
    messages: [boundary, ...recentMessages],
    summary,
    triggered: true,
    compactedCount: olderMessages.length,
  };
}

/**
 * Compact messages with a specific instruction focus.
 * User can specify what aspects to preserve in summary.
 */
export async function fullCompactWithFocus(
  messages: Message[],
  focus: string,
  config: FullCompactConfig = DEFAULT_FULL_COMPACT_CONFIG,
  modelClient?: {
    summarize: (prompt: string, maxTokens: number) => Promise<string>;
  }
): Promise<FullCompactResult> {
  if (messages.length <= config.windowMessages) {
    return {
      messages,
      summary: '',
      triggered: false,
      compactedCount: 0,
    };
  }

  const stripped = stripHeavyContent(messages);
  const recentMessages = stripped.slice(-config.windowMessages);
  const olderMessages = stripped.slice(0, -config.windowMessages);

  const textForSummary = extractTextForSummary(olderMessages);

  const prompt = `You are a conversation summarizer. Your task is to create a concise summary of the following conversation, with special focus on: ${focus}

## Requirements:
- Preserve information related to: ${focus}
- Preserve specific facts, names, dates, and technical details
- Keep the overall narrative and reasoning flow
- Note any important unresolved questions or follow-up items

## Conversation to Summarize:

${textForSummary}

## Summary:`;

  const summary = modelClient
    ? await modelClient.summarize(prompt, config.summaryMaxTokens)
    : `[Summary focused on ${focus} - In production, this would be generated by AI]`;

  const boundary = createBoundaryMessage(summary, olderMessages.length, recentMessages.length);

  return {
    messages: [boundary, ...recentMessages],
    summary,
    triggered: true,
    compactedCount: olderMessages.length,
  };
}
